### ISSUE TITLE
/machines directory is empty

### ISSUE THREAD

**Issue by BernhMueller** [RattyDAVE/alpine-simh#1]
When I start the container using Docker Desktop on a MacBook Pro Intel with Monterey, the /machines directory is empty.
Where are the install files? I am correctly presented with the /machines directory, but there is nothing in there

**Comment by RattyDAVE** [comment]
I had a quick look and it does seem something is not right. I will fix tomorrow.

**Comment by RattyDAVE** [comment]
FIXED... It seems github changed the way that you can clone repos.  out goes the git:// style and in with the https://

Try now!

**Comment by BernhMueller** [comment]
Thank you! Now it works.
