### ISSUE TITLE
3b2 emulator is missing and wrong location for disk files

### ISSUE THREAD

**Issue by crdotson** [RattyDAVE/alpine-simh#4]
The disk/nvram files now appear to be in a different location; I was going to put in a pull request to change the install script to:
wget https://archives.loomcom.com/3b2/emulator/extras_gnu_src.img.gz
gzip -d extras_gnu_src.img.gz
wget https://archives.loomcom.com/3b2/emulator/700/nvram.bin

However the simh-3.11.1-r1 package installed doesn't include a 3b2 binary now, so I think that's going to require a full build environment and building simh to fix; wasn't sure if you wanted to go that direction.  (Thanks for this image, by the way!)

**Comment by RattyDAVE** [comment]
OH thanks for pointing this out. One of the problem with this container is that it has got so complex that I cant monitor all parts now.

I will have an investigation. Later today.

**Comment by RattyDAVE** [comment]
Update: 

![image](https://github.com/RattyDAVE/alpine-simh/assets/9049822/30555eb8-5498-47bc-826d-1123785eefc3)

**Comment by RattyDAVE** [comment]
![image](https://github.com/RattyDAVE/alpine-simh/assets/9049822/35f77bc5-8cd1-4826-80db-3ca43a37e893)

**Comment by RattyDAVE** [comment]
New build is up and pushed and looking good. Have a look and let me know what you think.
